export default {
  header: [
    {
      link: "/collections.html",
      label: "San pham",
      dropdown: [
        {
          title: "Nhu cau",
          dropdownList: [
            "Coolgift",
            "Mac nha & Mac trong",
            "Mac hang ngay",
            "Do the thao",
            "Phu kien",
          ],
        },
        {
          title: "Danh muc",
          dropdownList: [
            "Coolgift",
            "Mac nha & Mac trong",
            "Mac hang ngay",
            "Do the thao",
            "Phu kien",
          ],
        },
        {
          title: "BST",
          dropdownList: [
            "Coolgift",
            "Mac nha & Mac trong",
            "Mac hang ngay",
            "Do the thao",
            "Phu kien",
          ],
        },
        {
          title: "Cong nghe",
          dropdownList: [
            "Coolgift",
            "Mac nha & Mac trong",
            "Mac hang ngay",
            "Do the thao",
            "Phu kien",
          ],
        },
      ],
    },
    {
      link: "#",
      label: "84Rising",
    },
    {
      link: "#",
      label: "CM24",
    },
    {
      link: "#",
      label: "Coolprint",
    },
    {
      link: "#",
      label: "Lookbook22",
    },
  ],
  collectionsItems: [
    {
      image: "./images/policy/filter-1.jpg",
      listing: "listings-1",
      name: "BST&nbsp;Thu&nbsp;Dong",
      tag: "BST Thu Dong",
      title: "Do Thu Dong",
      productItems: [
        {
          id: 1,
          images: ["./images/listing-1.jpg"],
          title: "",
          price: "",
          ratingStar: "",
          ratingNumber: "",
          select: "",
          action: "",
        },
        {
          id: 2,
          images: [
            "./images/listing-product-1a.jpg",
            "./images/listing-product-1.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 3,
          images: [
            "./images/listing-product-1a.jpg",
            "./images/listing-product-1.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 4,
          images: [
            "./images/listing-product-1a.jpg",
            "./images/listing-product-1.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
      ],
    },
    {
      image: "./images/filter-2.jpg",
      listing: "listings-2",
      name: "Ao&nbsp;nam",
      tag: "BST Thu Dong",
      title: "Do Thu Dong",
      productItems: [
        {
          id: 1,
          images: [
            "./images/listing-product-2.jpg",
            "./images/listing-product-2a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-2.jpg",
            "./images/listing-product-2a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-2.jpg",
            "./images/listing-product-2a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-2.jpg",
            "./images/listing-product-2a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
      ],
    },
    {
      image: "./images/filter-3.jpg",
      listing: "listings-3",
      name: "Quan&nbsp;nam",
      tag: "BST Thu Dong",
      title: "Do Thu Dong",
      productItems: [
        {
          id: 1,
          images: [
            "./images/listing-product-3.jpg",
            "./images/listing-product-3a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-3.jpg",
            "./images/listing-product-3a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-3.jpg",
            "./images/listing-product-3a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
        {
          id: 1,
          images: [
            "./images/listing-product-3.jpg",
            "./images/listing-product-3a.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
      ],
    },
    {
      image: "./images/filter-4.jpg",
      listing: "listings-4",
      name: "Quan&nbsp;lot",
      tag: "BST Thu Dong",
      title: "Do Thu Dong",
      productItems: [
        {
          id: 1,
          images: [
            "./images/listing-product-4.jpg",
            "./images/listing-product-1.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
      ],
    },
    {
      image: "./images/filter-5.jpg",
      listing: "listings-5",
      name: "Phu&nbsp;kien",
      tag: "Phu kien",
      title: "Phu kien",
      productItems: [
        {
          id: 1,
          images: [
            "./images/listing-product-1a.jpg",
            "./images/listing-product-1.jpg",
          ],
          title: "Áo thun nam dài tay Cotton Compact V2 - Xám",
          price: "280.000d",
          ratingStar: 4.8,
          ratingNumber: 194,
          select: ["M", "L", "XL", "2XL", "3XL"],
          action: "Mua 2 chi con 199k/chiec",
        },
      ],
    },
  ],
};
